version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: microservices_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: microservices_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin123'  # Минимум 8 символов
    volumes:
      - minio_data:/data
    networks:
      - microservices_network
    command: server /data --console-address ":9001"



  users_service:
    build: ./users_service
    container_name: users_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:postgres@postgres:5432/melo_users
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices_network
    volumes:
      - ./users_service:/app

  media_service:
    build: ./media_service
    container_name: media_service
    ports:
      - "8001:8001"
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ROOT_USER: 'minioadmin'        #  запустить пользовательскую консоль
      MINIO_ROOT_PASSWORD: 'minioadmin123'
      CDN_DOMAIN: "localhost:9000"
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    networks:
      - microservices_network
    volumes:
      - ./media_service:/app

  mongodb:
    image: mongo:7
    container_name: microservices_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: postgres
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  social_feed_service:
    build: ./social_feed_service
    container_name: social_feed_service
    ports:
      - "8002:8002"
    environment:
      MONGODB_URL: mongodb://admin:postgres@mongodb:27017/?authSource=admin
      MONGODB_DATABASE: melo_social
      USERS_SERVICE_URL: http://users_service:8000
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      mongodb:
        condition: service_healthy
      users_service:
        condition: service_started
    networks:
      - microservices_network
    volumes:
      - ./social_feed_service:/app

  comment_service:
    build: ./comment_service
    container_name: comment_service
    ports:
      - "8003:8003"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
    environment:
      MONGODB_URL: mongodb://admin:postgres@mongodb:27017/?authSource=admin
      MONGODB_DATABASE: melo_comments
      USERS_SERVICE_URL: http://users_service:8000
    depends_on:
      mongodb:
        condition: service_healthy
      users_service:
        condition: service_started
    networks:
      - microservices_network
    volumes:
      - ./comment_service:/app

  music_catalog_service:
    build: ./music_catalog_service
    container_name: music_catalog_service
    ports:
      - "8004:8004"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: postgres
      DB_NAME: melo_tracks
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices_network
    volumes:
      - ./music_catalog_service:/app

  frontend:
      build: ./frontend
      container_name: frontend
      ports:
        - "5173:5173"
      networks:
        - microservices_network
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        NODE_ENV: development
        CHOKIDAR_USEPOLLING: true
        VITE_API_URL: http://localhost:8080
      depends_on:
        gateway_service:
          condition: service_started

  gateway_service:
      build: ./gateway_service
      container_name: gateway_service
      ports:
        - "8080:8080"
      command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
      environment:
        USERS_SERVICE_URL: http://users_service:8000
        MEDIA_SERVICE_URL: http://media_service:8001
        SOCIAL_SERVICE_URL: http://social_feed_service:8002
        COMMENTS_SERVICE_URL: http://comment_service:8003
        CATALOG_SERVICE_URL: http://music_catalog_service:8004
        KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        SECRET_KEY: your-secret-key-change-in-production
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
        REFRESH_TOKEN_EXPIRE_DAYS: 7
      depends_on:
        users_service:
          condition: service_started
        media_service:
          condition: service_started
        social_feed_service:
          condition: service_started
        comment_service:
          condition: service_started
        music_catalog_service:
          condition: service_started
      networks:
        - microservices_network
      volumes:
        - ./gateway_service:/app

networks:
  microservices_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data:
  mongo_data: